pipeline {
    agent none
    stages {
        stage('Stop all docker containers') {
            agent {
                label 'ubuntu'
            }
            steps {
                sh 'docker stop $(docker ps -aq)'
            }
        }
        stage('Build') {
            agent { 
                dockerfile {
                    filename "Dockerfile"
                    label 'ubuntu'
                    args '-p 4000:4000'
                    additionalBuildArgs "-t app:${env.BUILD_NUMBER}"
                }
            }
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            agent { 
                dockerfile {
                    filename "Dockerfile"
                    label 'ubuntu'
                    args '-p 4000:4000'
                    additionalBuildArgs "-t app:${env.BUILD_NUMBER}"
                }
            }
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            agent { 
                dockerfile {
                    filename "Dockerfile"
                    label 'ubuntu'
                    args '-p 4000:4000'
                    additionalBuildArgs "-t app:${env.BUILD_NUMBER}"
                }
            }
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Run docker container') {
            agent {
                label 'ubuntu'
            }
            steps {
                sh 'docker run -d -p 4000:4000 app:${env.BUILD_NUMBER}'
            }
        }
    }
}
